#  sudo curl -SL https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
#  sudo chmod +x /usr/local/bin/docker-compose

version: '3.2'

# set env file

#x-common-variables: &common
#  ENTT_VERSION: 3.11.1
#  COMMON_COMMAND: |
#      /bin/sh -c apt-get update && apt-get -y --no-install-recommends install \
#      build-essential \
#      cmake \
#      gdb \
#      wget \
#      g++-11  \
#      pciutils

services:

#  build-cpu-ubuntu:
#    container_name: build-cpu-ubuntu
#    image: ubuntu/ubuntu:22.04
#    restart: unless-stopped
##    environment: *common-variables
#    environment:
#      ENTT_VERSION: 3.11.1
#      COMMON_COMMAND: |
#        /bin/sh -c apt-get update && apt-get -y --no-install-recommends install \
#        build-essential \
#        cmake \
#        gdb \
#        wget \
#        g++-11  \
#        pciutils
#    command:  |
#      ${COMMON_COMMAND} \
#      && wget https://github.com/skypjack/entt/archive/refs/tags/v${ENTT_VERSION}.tar.gz \
#      && tar -xvf v${ENTT_VERSION}.tar.gz \
#      && "while true; do echo Ready to build!; sleep 10; done"

  build-cuda118-ubuntu2204:
    container_name: build-cuda118-ubuntu2204
    volumes:
      - ${PWD}/prefix:/prefix
    build:
      context: .
      dockerfile: cuda-ubuntu-build.dockerfile
      args:
        - CUDA_VERSION=11.8.0
        - UBUNTU_VERSION=22.04
        - ENTT_VERSION=3.11.1
        - EIGEN_VERSION=3.4.0
#       mount prefix

    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - "cp -R /tmp_prefix/* /prefix"
#      - "while true; do echo Ready to run!; sleep 10; done"

#    mount /usr/local/cuda-11.8.0
#    volumes:


#  runtime-cpu-ubuntu:
#    container_name: runtime-cpu-ubuntu
#    image: ubuntu/ubuntu:22.04
#    deploy:
#      replicas: 1
#      restart_policy:
#        condition: unless-stopped
#    command: /bin/sh -c "while true; do echo Ready to run!; sleep 10; done"
#
#  runtime-gpu-ubuntu:
#    container_name: runtime-gpu-ubuntu
#    image: nvidia/cuda:11.8.0-devel-ubuntu22.04
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [ gpu ]
#      replicas: 1
#      restart_policy:
#        condition: unless-stopped
#    command: /bin/sh -c "while true; do nvidia-smi; sleep 10; done"
